environments:
  staging:
    required_approvals: 1
    deployers:
      - "@d12"
      - "@nwoodthorpe"
    approvers:
      - "@d12"
      - "@nwoodthorpe"

  prod:
    required_approvals: 2
    deployers:
      - "@d12"
    approvers:
      - "@d12"
      - "@nwoodthorpe"
